name: shadcn_flutter
description: 'Beautifully designed components from Shadcn/UI is now available for Flutter'
version: 0.0.30

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  skeletonizer: ^1.4.2
  syntax_highlight: ^0.4.0
  country_flags: ^3.0.0
  phonecodes: ^0.0.3
  cross_file: ^0.3.4+2
  image: ^4.2.0
  web: ^1.0.0
  data_widget: ^0.0.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icon_font_generator: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RadixIcons
      fonts:
        - asset: 'asset/icon/RadixIcons.otf'
    - family: BootstrapIcons
      fonts:
        - asset: 'asset/icon/BootstrapIcons.otf'
    - family: LucideIcons
      fonts:
        - asset: 'asset/icon/LucideIcons.ttf'
    - family: 'GeistSans'
      fonts:
        - asset: 'asset/font/Geist-Black.otf'
          weight: 800
        - asset: 'asset/font/Geist-Bold.otf'
          weight: 700
        - asset: 'asset/font/Geist-Light.otf'
          weight: 300
        - asset: 'asset/font/Geist-Medium.otf'
          weight: 500
        - asset: 'asset/font/Geist-SemiBold.otf'
          weight: 600
        - asset: 'asset/font/Geist-Thin.otf'
          weight: 100
        - asset: 'asset/font/Geist-UltraBlack.otf'
          weight: 900
        - asset: 'asset/font/Geist-UltraLight.otf'
          weight: 200
        - asset: 'asset/font/Geist-Regular.otf'
          weight: 400
    - family: 'GeistMono'
      fonts:
        - asset: 'asset/font/GeistMono-Black.otf'
          weight: 800
        - asset: 'asset/font/GeistMono-Bold.otf'
          weight: 700
        - asset: 'asset/font/GeistMono-Light.otf'
          weight: 300
        - asset: 'asset/font/GeistMono-Medium.otf'
          weight: 500
        - asset: 'asset/font/GeistMono-Regular.otf'
          weight: 400
        - asset: 'asset/font/GeistMono-SemiBold.otf'
          weight: 600
        - asset: 'asset/font/GeistMono-Thin.otf'
          weight: 100
        - asset: 'asset/font/GeistMono-UltraBlack.otf'
          weight: 900
        - asset: 'asset/font/GeistMono-UltraLight.otf'
          weight: 200

topics:
  - widgets
  - user-interface
  - design
  - components
  - shadcn-ui
